name = "Ayu Dark"

[colors]
accent     = "#39bae6"
link       = "#59c2ff"
success    = "#aad94c"
notice     = "#ff8f40"
bg         = "#0d1017"
bg_dark    = "#080c13"
text       = "#bfbdb6"
muted_text = "#6c7380"
border     = "#1a212c"
unread     = "#ffb454"
teal       = "#95e6cb"
sky        = "#59c2ff"
pink       = "#d2a6ff"
error      = "#f26d78"
