name = "Catppuccin Macchiato"

[colors]
accent     = "#c6a0f6"
link       = "#8aadf4"
success    = "#a6da95"
header     = "#f5a97f"
bg         = "#24273a"
bg_dark    = "#1e2030"
text       = "#cad3f5"
muted      = "#a5adcb"
border     = "#363a4f"
warning    = "#eed49f"
code       = "#8bd5ca"
sky        = "#91d7e3"
pink       = "#f5bde6"
error      = "#ed8796"
selection  = "#363a4f"
code_bg    = "#1e2030"
