name = "Catppuccin Latte"

[colors]
accent     = "#8839ef"
link       = "#1e66f5"
success    = "#40a02b"
header     = "#fe640b"
bg         = "#eff1f5"
bg_dark    = "#e6e9ef"
text       = "#4c4f69"
muted      = "#7c7f93"
border     = "#ccd0da"
warning    = "#df8e1d"
code       = "#179299"
sky        = "#04a5e5"
pink       = "#ea76cb"
error      = "#d20f39"
selection  = "#ccd0da"
code_bg    = "#e6e9ef"
