name = "Dracula"

[colors]
accent     = "#bd93f9"
link       = "#6272a4"
success    = "#50fa7b"
header     = "#ffb86c"
bg         = "#282a36"
bg_dark    = "#191a21"
text       = "#f8f8f2"
muted      = "#6272a4"
border     = "#44475a"
warning    = "#f1fa8c"
code       = "#8be9fd"
sky        = "#8be9fd"
pink       = "#ff79c6"
error      = "#ff5555"
selection  = "#44475a"
code_bg    = "#191a21"
