name = "Everforest"

[colors]
accent     = "#a7c080"
link       = "#7fbbb3"
success    = "#a7c080"
header     = "#e69875"
bg         = "#2d353b"
bg_dark    = "#272e33"
text       = "#d3c6aa"
muted      = "#859289"
border     = "#3d484d"
warning    = "#dbbc7f"
code       = "#7fbbb3"
sky        = "#83c092"
pink       = "#e67e80"
error      = "#e67e80"
selection  = "#3d484d"
code_bg    = "#272e33"
