name = "Everforest"

[colors]
accent     = "#a7c080"
link       = "#7fbbb3"
success    = "#a7c080"
header     = "#e69875"
bg         = "#333c43"
bg_dark    = "#293136"
text       = "#d3c6aa"
muted      = "#859289"
border     = "#434f55"
warning    = "#dbbc7f"
code       = "#7fbbb3"
sky        = "#83c092"
pink       = "#e67e80"
error      = "#e67e80"
selection  = "#434f55"
code_bg    = "#293136"
