name = "Gruvbox Light"

[colors]
accent     = "#b16286"
link       = "#076678"
success    = "#79740e"
header     = "#af3a03"
bg         = "#fbf1c7"
bg_dark    = "#f2e5bc"
text       = "#3c3836"
muted      = "#7c6f64"
border     = "#d5c4a1"
warning    = "#b57614"
code       = "#427b58"
sky        = "#458588"
pink       = "#8f3f71"
error      = "#cc241d"
selection  = "#d5c4a1"
code_bg    = "#f2e5bc"
