name = "Horizon"

[colors]
accent     = "#e95678"
link       = "#26bbd9"
success    = "#29d398"
header     = "#fab795"
bg         = "#1c1e26"
bg_dark    = "#16181f"
text       = "#d5d8da"
muted      = "#6c6f93"
border     = "#2e303e"
warning    = "#fac29a"
code       = "#26bbd9"
sky        = "#59e1e3"
pink       = "#ee64ac"
error      = "#e95678"
selection  = "#2e303e"
code_bg    = "#16181f"
