name = "Kanagawa Wave"

[colors]
accent     = "#957fb8"
link       = "#7e9cd8"
success    = "#76946a"
header     = "#ffa066"
bg         = "#1f1f28"
bg_dark    = "#16161d"
text       = "#dcd7ba"
muted      = "#727169"
border     = "#2a2a37"
warning    = "#dca561"
code       = "#6a9589"
sky        = "#7fb4ca"
pink       = "#d27e99"
error      = "#c34043"
selection  = "#2a2a37"
code_bg    = "#16161d"
