name = "Melange Dark"

[colors]
accent     = "#e49b5d"
link       = "#78b9a2"
success    = "#78b9a2"
notice     = "#d4956a"
bg         = "#352a21"
bg_dark    = "#2a2117"
text       = "#ecebe5"
muted_text = "#a38d78"
border     = "#4a3c30"
unread     = "#e8b96e"
teal       = "#78b9a2"
sky        = "#9bbdd2"
pink       = "#cf9bc2"
error      = "#cf6f70"
