name = "Monokai"

[colors]
accent     = "#ae81ff"
link       = "#66d9e8"
success    = "#a6e22e"
header     = "#fd971f"
bg         = "#272822"
bg_dark    = "#1e1f1c"
text       = "#f8f8f2"
muted      = "#75715e"
border     = "#3e3d32"
warning    = "#e6db74"
code       = "#66d9e8"
sky        = "#66d9e8"
pink       = "#f92672"
error      = "#f92672"
selection  = "#3e3d32"
code_bg    = "#1e1f1c"
