name = "Nightfly"

[colors]
accent     = "#82aaff"
link       = "#7fdbca"
success    = "#22da6e"
notice     = "#ecc48d"
bg         = "#011627"
bg_dark    = "#010e1a"
text       = "#acb4c2"
muted_text = "#637777"
border     = "#1d3b53"
unread     = "#ffcb8b"
teal       = "#7fdbca"
sky        = "#87d7ff"
pink       = "#c792ea"
error      = "#ff5874"
