name = "One Light"

[colors]
accent     = "#a626a4"
link       = "#4078f2"
success    = "#50a14f"
notice     = "#986801"
bg         = "#fafafa"
bg_dark    = "#e5e5e6"
text       = "#383a42"
muted_text = "#a0a1a7"
border     = "#d3d3d3"
unread     = "#c18401"
teal       = "#0184bc"
sky        = "#4078f2"
pink       = "#e45649"
error      = "#e45649"
