name = "One Light"

[colors]
accent     = "#a626a4"
link       = "#4078f2"
success    = "#50a14f"
header     = "#986801"
bg         = "#fafafa"
bg_dark    = "#e5e5e6"
text       = "#383a42"
muted      = "#696c77"
border     = "#d3d3d3"
warning    = "#8a5d00"
code       = "#0184bc"
sky        = "#4078f2"
pink       = "#e45649"
error      = "#e45649"
selection  = "#d3d3d3"
code_bg    = "#e5e5e6"
