name = "Oxocarbon"

[colors]
accent     = "#be95ff"
link       = "#78a9ff"
success    = "#42be65"
header     = "#ff832b"
bg         = "#161616"
bg_dark    = "#0d0d0d"
text       = "#f4f4f4"
muted      = "#8d8d8d"
border     = "#262626"
warning    = "#f1c21b"
code       = "#3ddbd9"
sky        = "#78a9ff"
pink       = "#ff7eb6"
error      = "#fa4d56"
selection  = "#262626"
code_bg    = "#0d0d0d"
