name = "Palenight"

[colors]
accent     = "#c792ea"
link       = "#82aaff"
success    = "#c3e88d"
notice     = "#ffcb6b"
bg         = "#292d3e"
bg_dark    = "#1b1e2b"
text       = "#a6accd"
muted_text = "#676e95"
border     = "#434758"
unread     = "#ffcb6b"
teal       = "#89ddff"
sky        = "#82aaff"
pink       = "#f07178"
error      = "#f07178"
