name = "Powershell"

[colors]
accent     = "#ffff00"
link       = "#569cd6"
success    = "#00ff00"
header     = "#00ffff"
bg         = "#012456"
bg_dark    = "#000e1e"
text       = "#eeeeee"
muted      = "#c0c0c0"
border     = "#003399"
warning    = "#ffff00"
code       = "#00ffff"
sky        = "#569cd6"
pink       = "#ff00ff"
error      = "#ff0000"
selection  = "#003399"
code_bg    = "#000e1e"
