name = "Powershell"

[colors]
accent     = "#fefe45"
link       = "#268ad2"
success    = "#1cfe3c"
header     = "#29fffe"
bg         = "#052454"
bg_dark    = "#031837"
text       = "#f6f6f7"
muted      = "#c2c1c3"
border     = "#0e3a7a"
warning    = "#c4a000"
code       = "#0e807f"
sky        = "#4140c3"
pink       = "#fe13fa"
error      = "#ef2929"
selection  = "#0e3a7a"
code_bg    = "#031837"
