name = "Rose Pine"

[colors]
accent     = "#c4a7e7"
link       = "#9ccfd8"
success    = "#31748f"
header     = "#f6c177"
bg         = "#191724"
bg_dark    = "#0f0d16"
text       = "#e0def4"
muted      = "#6e6a86"
border     = "#26233a"
warning    = "#f6c177"
code       = "#9ccfd8"
sky        = "#9ccfd8"
pink       = "#eb6f92"
error      = "#eb6f92"
selection  = "#26233a"
code_bg    = "#0f0d16"
