name = "Rose Pine Dawn"

[colors]
accent     = "#907aa9"
link       = "#56949f"
success    = "#286983"
header     = "#ea9d34"
bg         = "#faf4ed"
bg_dark    = "#ede0d4"
text       = "#575279"
muted      = "#6e6a86"
border     = "#dfdad9"
warning    = "#8a5c0a"
code       = "#56949f"
sky        = "#56949f"
pink       = "#b4637a"
error      = "#b4637a"
selection  = "#dfdad9"
code_bg    = "#ede0d4"
