name = "Solarized Light"

[colors]
accent     = "#268bd2"
link       = "#2aa198"
success    = "#859900"
header     = "#cb4b16"
bg         = "#fdf6e3"
bg_dark    = "#eee8d5"
text       = "#657b83"
muted      = "#93a1a1"
border     = "#d9d2bc"
warning    = "#7a5c00"
code       = "#2aa198"
sky        = "#268bd2"
pink       = "#d33682"
error      = "#dc322f"
selection  = "#d9d2bc"
code_bg    = "#eee8d5"
