name = "Solarized Dark"

[colors]
accent     = "#268bd2"
link       = "#2aa198"
success    = "#859900"
notice     = "#cb4b16"
bg         = "#073642"
bg_dark    = "#002b36"
text       = "#839496"
muted_text = "#586e75"
border     = "#073642"
unread     = "#b58900"
teal       = "#2aa198"
sky        = "#268bd2"
pink       = "#d33682"
error      = "#dc322f"
