name = "Synthwave '84"

[colors]
accent     = "#f97e72"
link       = "#36f9f6"
success    = "#72f1b8"
notice     = "#fede5d"
bg         = "#262335"
bg_dark    = "#1a1a2e"
text       = "#ffffff"
muted_text = "#848bbd"
border     = "#495495"
unread     = "#fede5d"
teal       = "#36f9f6"
sky        = "#2ee2fa"
pink       = "#fe4450"
error      = "#fe4450"
