name = "Synthwave '84"

[colors]
accent     = "#f97e72"
link       = "#36f9f6"
success    = "#72f1b8"
header     = "#fede5d"
bg         = "#262335"
bg_dark    = "#1a1a2e"
text       = "#ffffff"
muted      = "#848bbd"
border     = "#495495"
warning    = "#fede5d"
code       = "#36f9f6"
sky        = "#2ee2fa"
pink       = "#fe4450"
error      = "#fe4450"
selection  = "#495495"
code_bg    = "#1a1a2e"
