name = "Tokyo Night"

[colors]
accent     = "#7aa2f7"
link       = "#7dcfff"
success    = "#9ece6a"
header     = "#ff9e64"
bg         = "#1a1b26"
bg_dark    = "#16161e"
text       = "#c0caf5"
muted      = "#565f89"
border     = "#292e42"
warning    = "#e0af68"
code       = "#2ac3de"
sky        = "#7dcfff"
pink       = "#bb9af7"
error      = "#f7768e"
selection  = "#292e42"
code_bg    = "#16161e"
