name = "Tokyo Night Storm"

[colors]
accent     = "#7aa2f7"
link       = "#7dcfff"
success    = "#9ece6a"
header     = "#ff9e64"
bg         = "#24283b"
bg_dark    = "#1f2335"
text       = "#c0caf5"
muted      = "#565f89"
border     = "#3b4261"
warning    = "#e0af68"
code       = "#2ac3de"
sky        = "#7dcfff"
pink       = "#bb9af7"
error      = "#f7768e"
selection  = "#3b4261"
code_bg    = "#1f2335"
