#!/usr/bin/env python3
"""Capture README screenshots of brochure: several themes and several views.

Each screenshot is a fresh app launch. Because VHS occasionally drops or
double-fires keypresses, every capture is verified (active tab / mode) and
retried with a fresh launch until it shows the intended view.

Views:
  main      three-pane article reader (Feeds tab)
  saved     Saved tab with a saved article open
  settings  Settings tab
  changelog Changelog/About tab
  zen       full-screen zen reading mode

Usage (from repo root):
    python3 scripts/screenshot_themes.py [view ...]

Requires: vhs on PATH, a built release binary at target/release/brochure,
and a populated brochure data dir (~/.local/share/brochure).
"""
import json
import os
import subprocess
import sys
from PIL import Image

VHS = os.environ.get('VHS', 'vhs')
# Fall back to common install locations when vhs isn't on PATH.
if subprocess.run(['which', VHS], capture_output=True).returncode != 0:
    for candidate in ('~/go/bin/vhs', '/usr/local/bin/vhs', '/home/linuxbrew/.linuxbrew/bin/vhs'):
        p = os.path.expanduser(candidate)
        if os.path.exists(p):
            VHS = p
            break

DATA_DIR = os.path.expanduser('~/.local/share/brochure')
USER_DATA = os.path.join(DATA_DIR, 'user_data.json')
OUT_DIR = 'vhs/screenshots'

TAPE_TEMPLATE = """# brochure screenshot: {view} ({theme})
# Generated by scripts/screenshot_themes.py — do not edit by hand.
Set Theme "Aardvark Blue"
Set Width 1200
Set Height 900
Set Padding 0
# 1 fps: only the final Screenshot is used, and a low capture rate keeps VHS
# fast (24 fps recording of a 1200x900 terminal is very CPU-heavy).
Set Framerate 1

Hide
Type "./target/release/brochure"
Enter
Sleep 1s
Show
Sleep 3s
{keys}Screenshot vhs/screenshots/{view}-{theme}.png
Sleep 1s
"""

# (view, theme, key commands, description)
VIEWS = [
    ('main', 'catppuccin-mocha', 'Enter\nSleep 1s\nEnter\nSleep 1s\nEnter\nSleep 3s\n',
     'three-pane article view'),
    ('main', 'tokyo-night', 'Enter\nSleep 1s\nEnter\nSleep 1s\nEnter\nSleep 3s\n',
     'three-pane article view'),
    ('main', 'solarized-light', 'Enter\nSleep 1s\nEnter\nSleep 1s\nEnter\nSleep 3s\n',
     'three-pane article view'),
    ('saved', 'dracula', 'Tab\nSleep 1.5s\nEnter\nSleep 1s\nEnter\nSleep 1s\nEnter\nSleep 3s\n',
     'saved articles'),
    ('settings', 'nord', 'Tab\nSleep 1.5s\nTab\nSleep 1.5s\nSleep 2s\n',
     'settings'),
    ('changelog', 'rose-pine', 'Tab\nSleep 1.5s\nTab\nSleep 1.5s\nTab\nSleep 1.5s\nSleep 2s\n',
     'changelog and about'),
    ('zen', 'catppuccin-latte', 'Enter\nSleep 1s\nEnter\nSleep 1s\nEnter\nSleep 1s\nType "z"\nSleep 3s\n',
     'zen reading mode'),
]

TAB_BLOCK_Y = 28
# Active-tab background block x-ranges at 1200x900 / FontSize 14 (see chrome.rs).
TAB_RANGES = {'Feeds': (160, 261), 'Saved': (275, 376), 'Settings': (390, 534), 'Changelog': (549, 693)}


def tab_blocks(im):
    """Light background blocks in the tab bar row, excluding the Brochure brand block."""
    bg = im.getpixel((1100, TAB_BLOCK_Y))
    row = [im.getpixel((x, TAB_BLOCK_Y)) for x in range(0, 800)]
    runs = []
    inrun = False
    for idx, c in enumerate(row):
        if abs(c[0] - bg[0]) + abs(c[1] - bg[1]) + abs(c[2] - bg[2]) > 60:
            if not inrun:
                start = idx
                inrun = True
        else:
            if inrun:
                runs.append((start, idx - 1))
                inrun = False
    if inrun:
        runs.append((start, 799))
    # Ignore tiny text artifacts; keep runs that could be an active-tab block.
    return [r for r in runs if r[1] - r[0] > 30]


def active_tab(im):
    blocks = tab_blocks(im)
    if not blocks:
        return None  # no tab bar (zen mode)
    # Match each block against the known tab ranges (the Brochure brand block
    # matches none and is ignored).
    for name, (lo, hi) in TAB_RANGES.items():
        center = (lo + hi) / 2
        for s, e in blocks:
            if center - 40 <= (s + e) / 2 <= center + 40:
                return name
    return 'unknown'


def article_visible(im):
    """True when the right-hand article pane shows rendered text."""
    crop = im.crop((760, 300, 1180, 850))
    return len(crop.getcolors(maxcolors=1 << 20) or []) > 200


def verify(view, im):
    if view == 'zen':
        return active_tab(im) is None
    want = {'main': 'Feeds', 'saved': 'Saved', 'settings': 'Settings', 'changelog': 'Changelog'}[view]
    tab = active_tab(im)
    if tab != want:
        return False
    if view == 'main':
        return article_visible(im)
    return True


def set_theme(slug: str) -> None:
    with open(USER_DATA) as f:
        data = json.load(f)
    data['selected_theme'] = slug
    with open(USER_DATA, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    selected = sys.argv[1:]
    views = [v for v in VIEWS if not selected or v[0] in selected]
    if not views:
        print('no views matched')
        return 1

    for view, theme, keys, desc in views:
        print(f'--- {view} ({theme}) ---')
        for attempt in range(1, 6):
            set_theme(theme)
            tape = os.path.join(OUT_DIR, f'{view}-{theme}.tape')
            with open(tape, 'w') as f:
                f.write(TAPE_TEMPLATE.format(view=view, theme=theme, keys=keys))
            r = subprocess.run([VHS, tape], capture_output=True, text=True, timeout=90)
            if r.returncode != 0:
                print('  vhs failed:', r.stderr[-400:])
                break
            png = os.path.join(OUT_DIR, f'{view}-{theme}.png')
            im = Image.open(png).convert('RGB')
            tab = active_tab(im)
            if verify(view, im):
                print(f'  {png}: {os.path.getsize(png) // 1024} KiB (tab={tab})')
                break
            print(f'  attempt {attempt}: tab={tab}, retrying...')
        else:
            print(f'  giving up on {view} ({theme}) after 5 attempts')

    set_theme('catppuccin-mocha')
    print('done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
