#!/usr/bin/env python3
"""Capture README screenshots of brochure in a selection of built-in themes.

For each theme:
1. Sets `selected_theme` in the user data file (brochure reads it at startup).
2. Runs a VHS tape that launches the app, opens the first article, and
   screenshots the three-pane view.

Usage (from repo root):
    python3 scripts/screenshot_themes.py [theme ...]

Requires: vhs on PATH, a built release binary at target/release/brochure,
and a populated brochure data dir (~/.local/share/brochure).
"""
import json
import os
import subprocess
import sys
from PIL import Image

VHS = os.environ.get('VHS', 'vhs')
# Fall back to common install locations when vhs isn't on PATH.
if subprocess.run(['which', VHS], capture_output=True).returncode != 0:
    for candidate in ('~/go/bin/vhs', '/usr/local/bin/vhs', '/home/linuxbrew/.linuxbrew/bin/vhs'):
        p = os.path.expanduser(candidate)
        if os.path.exists(p):
            VHS = p
            break
DATA_DIR = os.path.expanduser('~/.local/share/brochure')
USER_DATA = os.path.join(DATA_DIR, 'user_data.json')
OUT_DIR = 'vhs/screenshots'

# (slug, display name) — a mix of dark and light built-ins.
THEMES = [
    ('catppuccin-mocha', 'Catppuccin Mocha'),
    ('tokyo-night', 'Tokyo Night'),
    ('dracula', 'Dracula'),
    ('nord', 'Nord'),
    ('rose-pine', 'Rose Pine'),
    ('solarized-light', 'Solarized Light'),
    ('catppuccin-latte', 'Catppuccin Latte'),
]

TAPE_TEMPLATE = """# brochure theme screenshot: {theme}
# Generated by scripts/screenshot_themes.py — do not edit by hand.
Set Theme "Aardvark Blue"
Set Width 1200
Set Height 900
Set Padding 0
Set Framerate 24

Hide
Type "./target/release/brochure"
Enter
Sleep 1s
Show
Sleep 3s
# Enter is a no-op in ArticleDetail, so pressing it three times guarantees the
# article opens even if VHS drops one or two keypresses (see screenshot_themes.py).
Enter # All Feeds -> article list
Sleep 1s
Enter # article list -> article detail
Sleep 1s
Enter # no-op once the article is open
Sleep 3s
Screenshot vhs/screenshots/{theme}.png
Sleep 1s
"""


def set_theme(slug: str) -> None:
    with open(USER_DATA) as f:
        data = json.load(f)
    data['selected_theme'] = slug
    with open(USER_DATA, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')


def article_visible(png: str) -> bool:
    """True when the right-hand article pane shows rendered text."""
    im = Image.open(png).convert('RGB')
    # Right pane article body region (below the title block).
    crop = im.crop((760, 300, 1180, 850))
    # A blank pane is uniform; rendered text yields many distinct colours.
    return len(crop.getcolors(maxcolors=1 << 20) or []) > 200


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    selected = sys.argv[1:]
    themes = [t for t in THEMES if not selected or t[0] in selected]
    if not themes:
        print('no themes matched')
        return 1

    for slug, name in themes:
        print(f'--- {name} ({slug}) ---')
        for attempt in range(1, 5):
            set_theme(slug)
            tape = os.path.join(OUT_DIR, f'{slug}.tape')
            with open(tape, 'w') as f:
                f.write(TAPE_TEMPLATE.format(theme=slug))
            r = subprocess.run([VHS, tape], capture_output=True, text=True)
            if r.returncode != 0:
                print('  vhs failed:', r.stderr[-400:])
                break
            png = os.path.join(OUT_DIR, f'{slug}.png')
            if os.path.exists(png) and article_visible(png):
                print(f'  {png}: {os.path.getsize(png) // 1024} KiB (article open)')
                break
            print(f'  attempt {attempt}: article did not open, retrying...')
        else:
            print(f'  giving up on {name} after 4 attempts')

    # Restore the default theme so future runs look normal.
    set_theme('catppuccin-mocha')
    print('done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
